version: '3.4'

services:
  db:
    image: postgres
    container_name: nestdb
    ports:
        - 5434:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: nest
        POSTGRES_ROOT: root
        POSTGRES_ROOT_PASSWORD: root
    networks:
        - nesnet
networks:
    nesnet: